#include "EnemyAI.h"
#include "Enemy.h"
#include "OccupiedTerritory.h"

// AI ë° ë¹„í—¤ì´ë¹„ì–´ íŠ¸ë¦¬ ê´€ë ¨
#include "BehaviorTree/BlackboardComponent.h"
#include "BehaviorTree/BehaviorTree.h"
#include "BehaviorTree/BehaviorTreeComponent.h"

// ì¸ì‹ ì‹œìŠ¤í…œ
#include "Perception/AIPerceptionComponent.h"
#include "Perception/AISenseConfig_Sight.h"

// ë„¤ë¹„ê²Œì´ì…˜ ë° ì´ë™
#include "NavigationSystem.h"
#include "Navigation/PathFollowingComponent.h"
#include "AITypes.h"

// ì—”ì§„ ì½”ì–´
#include "Engine/World.h"
#include "Engine/Engine.h"
#include "Kismet/GameplayStatics.h"
#include "GameFramework/Character.h"
#include "GameFramework/CharacterMovementComponent.h"

// ë””ë²„ê·¸ ë° ìœ í‹¸ë¦¬í‹°
#include "DrawDebugHelpers.h"

// ë¸”ë™ë³´ë“œ í‚¤ ì´ë¦„ ìƒìˆ˜ ì •ì˜
const FName AEnemyAI::BB_IsInCombat(TEXT("IsInCombat"));
const FName AEnemyAI::BB_IsAlert(TEXT("IsAlert"));
const FName AEnemyAI::BB_IsBurstFiring(TEXT("IsBurstFiring"));
const FName AEnemyAI::BB_TargetActor(TEXT("TargetActor"));
const FName AEnemyAI::BB_LastKnownPlayerLocation(TEXT("LastKnownPlayerLocation"));
const FName AEnemyAI::BB_FireDistance(TEXT("FireDistance"));
const FName AEnemyAI::BB_SelfActor(TEXT("SelfActor"));

// ë””ë²„ê·¸ìš© ì½˜ì†” ë³€ìˆ˜ ì„ ì–¸
static TAutoConsoleVariable<int32> CVarShowEnemyAIDebug(
    TEXT("ai.ShowEnemyAIDebug"),
    0,
    TEXT("Show Enemy AI debug information\n")
    TEXT("0: Disabled\n")
    TEXT("1: Enabled"),
    ECVF_Default
);

AEnemyAI::AEnemyAI()
{
    PrimaryActorTick.bCanEverTick = true;

    // === AI ì¸ì‹ ì»´í¬ë„ŒíŠ¸ ì´ˆê¸°í™” ===
    AIPerceptionComp = CreateDefaultSubobject<UAIPerceptionComponent>(TEXT("AIPerceptionComponent"));

    // ì‹œê° ê°ì§€ ì„¤ì •
    UAISenseConfig_Sight* sightConfig = CreateDefaultSubobject<UAISenseConfig_Sight>(TEXT("SightConfig"));
    if (sightConfig)
    {
        sightConfig->SightRadius = sightRadius;
        sightConfig->LoseSightRadius = loseSightRadius;
        sightConfig->PeripheralVisionAngleDegrees = peripheralVisionAngle;
        sightConfig->DetectionByAffiliation.bDetectEnemies = true;
        sightConfig->DetectionByAffiliation.bDetectFriendlies = true;
        sightConfig->DetectionByAffiliation.bDetectNeutrals = true;
        sightConfig->SetMaxAge(3.0f);

        AIPerceptionComp->ConfigureSense(*sightConfig);
        AIPerceptionComp->SetDominantSense(sightConfig->GetSenseImplementation());
    }

    // === ë³€ìˆ˜ ì´ˆê¸°í™” ===
    currentTargetTerritory = nullptr;
    controlledPawn = nullptr;
    controlledEnemy = nullptr;
    
    // TPS Kit GASP ì‹œìŠ¤í…œ ìƒíƒœ ì´ˆê¸°í™”
    isInCombat = false;
    isAlert = false;
    isPatrolling = true;
    isBurstFiring = false;
    
    // íƒ€ê²Ÿ ì¶”ì  ì´ˆê¸°í™”
    currentTarget = nullptr;
    lastKnownTargetLocation = FVector::ZeroVector;
    lastTargetSeenTime = 0.0f;
    
    // íƒ€ì´ë¨¸ ì´ˆê¸°í™”
    alertTimer = 0.0f;
    combatTimer = 0.0f;
}

void AEnemyAI::BeginPlay()
{
    Super::BeginPlay();

    // === í•„ìˆ˜ ì»´í¬ë„ŒíŠ¸ ê²€ì¦ ===
    if (!AIPerceptionComp)
    {
        UE_LOG(LogTemp, Error, TEXT("EnemyAI: AI Perception Componentê°€ ì¡´ì¬í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤."));
        return;
    }

    if (!GetWorld())
    {
        UE_LOG(LogTemp, Error, TEXT("EnemyAI: Worldê°€ ì¡´ì¬í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤."));
        return;
    }

    // === ë‚´ë¹„ê²Œì´ì…˜ ì‹œìŠ¤í…œ ê²€ì¦ ===
    UNavigationSystemV1* navSystem = UNavigationSystemV1::GetCurrent(GetWorld());
    if (!navSystem)
    {
        UE_LOG(LogTemp, Warning, TEXT("EnemyAI: Navigation Systemì´ ì¡´ì¬í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤."));
    }

    // === ê²½ë¡œ ì¶”ì  ì»´í¬ë„ŒíŠ¸ ê²€ì¦ ===
    if (!GetPathFollowingComponent())
    {
        UE_LOG(LogTemp, Warning, TEXT("EnemyAI: Path Following Componentê°€ ì¡´ì¬í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤."));
    }

    // === ì¸ì‹ ì´ë²¤íŠ¸ ì½œë°± ë“±ë¡ ===
    if (AIPerceptionComp)
    {
        AIPerceptionComp->OnTargetPerceptionUpdated.AddDynamic(this, &AEnemyAI::OnPerceptionUpdated);
    }

    UE_LOG(LogTemp, Log, TEXT("EnemyAI: ì´ˆê¸°í™” ì™„ë£Œ"));
}

void AEnemyAI::Tick(float deltaTime)
{
    Super::Tick(deltaTime);

    // === ğŸ”§ ì´ë™ ê´€ë ¨ ì½”ë“œ ì œê±°, ë¸”ë™ë³´ë“œ ë™ê¸°í™”ë§Œ ìœ ì§€ ===
    // ë¸”ë™ë³´ë“œ ë™ê¸°í™”ëŠ” ë¹„í—¤ì´ë¹„ì–´ íŠ¸ë¦¬ê°€ ìˆì„ ë•Œë§Œ
    if (BehaviorTree && GetBlackboardComponent())
    {
        SyncEnemyStateWithBlackboard();
        UpdateTargetDistance();
    }

    // === ë””ë²„ê·¸ ì •ë³´ í‘œì‹œ ===
    DisplayDebugInfo();
}

void AEnemyAI::OnPossess(APawn* InPawn)
{
    Super::OnPossess(InPawn);

    // === ì œì–´í•  í° ì°¸ì¡° ì„¤ì • ===
    controlledPawn = InPawn;
    controlledEnemy = Cast<AEnemy>(InPawn);
    
    if (!controlledPawn)
    {
        UE_LOG(LogTemp, Error, TEXT("EnemyAI: ì œì–´í•  í°ì´ nullì…ë‹ˆë‹¤!"));
        return;
    }

    if (!controlledEnemy)
    {
        UE_LOG(LogTemp, Warning, TEXT("EnemyAI: í°ì´ Enemy í´ë˜ìŠ¤ê°€ ì•„ë‹™ë‹ˆë‹¤!"));
    }

    // === ğŸ”§ ì´ë™ ê´€ë ¨ ì´ˆê¸°í™” ì œê±° ===
    
    // === ê²½ë¡œ ì´ë™ ì„¤ì • ===
    if (GetPathFollowingComponent())
    {
        GetPathFollowingComponent()->SetAcceptanceRadius(acceptanceRadius);
    }

    // === ë¹„í—¤ì´ë¹„ì–´ íŠ¸ë¦¬ ì‹œìŠ¤í…œ ì´ˆê¸°í™” ===
    if (BehaviorTree && blackboardData)
    {
        // ğŸ”§ ìˆ˜ì •ëœ ë¸”ë™ë³´ë“œ ì‚¬ìš© ë°©ë²•
        if (UBlackboardComponent* BlackboardComp = GetBlackboardComponent())
        {
            BlackboardComp->InitializeBlackboard(*blackboardData);
            UE_LOG(LogTemp, Log, TEXT("EnemyAI: ë¸”ë™ë³´ë“œ ì´ˆê¸°í™” ì™„ë£Œ"));
        }
        
        // ë¸”ë™ë³´ë“œ ì´ˆê¸°ê°’ ì„¤ì •
        UBlackboardComponent* blackboardComp = GetBlackboardComponent();
        if (blackboardComp)
        {
            // ë¸”ë™ë³´ë“œ ì»´í¬ë„ŒíŠ¸ê°€ ì—†ëŠ” ê²½ìš° ìƒì„±
            UseBlackboard(blackboardData, blackboardComp);

            // ê¸°ë³¸ ë¸”ë™ë³´ë“œ ê°’ ì„¤ì •
            blackboardComp->SetValueAsObject(BB_SelfActor, controlledPawn);
            blackboardComp->SetValueAsBool(BB_IsInCombat, false);
            blackboardComp->SetValueAsBool(BB_IsAlert, false);
            blackboardComp->SetValueAsBool(BB_IsBurstFiring, false);
            blackboardComp->SetValueAsFloat(BB_FireDistance, 0.0f);
            
            UE_LOG(LogTemp, Log, TEXT("EnemyAI: ë¸”ë™ë³´ë“œ ê¸°ë³¸ê°’ ì„¤ì • ì™„ë£Œ"));
        }
        
        // ë¹„í—¤ì´ë¹„ì–´ íŠ¸ë¦¬ ì‹¤í–‰
        RunBehaviorTree(BehaviorTree);
        UE_LOG(LogTemp, Log, TEXT("EnemyAI: ë¹„í—¤ì´ë¹„ì–´ íŠ¸ë¦¬ ì‹œì‘"));
    }
    else
    {
        UE_LOG(LogTemp, Warning, TEXT("EnemyAI: BehaviorTree ë˜ëŠ” BlackboardDataê°€ ì„¤ì •ë˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤!"));
    }

    UE_LOG(LogTemp, Log, TEXT("EnemyAI: Pawn ì œì–´ ì‹œì‘"));
}

void AEnemyAI::OnUnPossess()
{
    Super::OnUnPossess();
    
    controlledPawn = nullptr;
    controlledEnemy = nullptr;
    currentTargetTerritory = nullptr;
    currentTarget = nullptr;
    
    UE_LOG(LogTemp, Log, TEXT("EnemyAI: Pawn ì œì–´ í•´ì œ"));
}

// === TPS Kit GASP ì‹œìŠ¤í…œ - ìƒíƒœ ê´€ë¦¬ ===

void AEnemyAI::EnterCombatState(AActor* Target)
{
    if (!Target || !controlledEnemy) return;

    // === Combat ìƒíƒœë¡œ ì „í™˜ ===
    isInCombat = true;
    isAlert = false;
    isPatrolling = false;
    
    currentTarget = Target;
    lastKnownTargetLocation = Target->GetActorLocation();
    lastTargetSeenTime = GetWorld()->GetTimeSeconds();
    
    // === Enemy ê°ì²´ì— ì „íˆ¬ ëª¨ë“œ ì§„ì… ì•Œë¦¼ ===
    controlledEnemy->EnterCombatMode(Target);
    
    // === ë¸”ë™ë³´ë“œ IsInCombatì„ trueë¡œ ì¦‰ì‹œ ì„¤ì • ===
    if (UBlackboardComponent* blackboardComp = GetBlackboardComponent())
    {
        blackboardComp->SetValueAsBool(BB_IsInCombat, true);
        blackboardComp->SetValueAsObject(BB_TargetActor, Target);
        blackboardComp->SetValueAsVector(BB_LastKnownPlayerLocation, Target->GetActorLocation());
        blackboardComp->SetValueAsBool(BB_IsAlert, false); // Combat ì¤‘ì—ëŠ” Alert í•´ì œ
        
        UE_LOG(LogTemp, Warning, TEXT("EnemyAI: ë¸”ë™ë³´ë“œ IsInCombat = true ì„¤ì •"));
    }
    
    UE_LOG(LogTemp, Warning, TEXT("EnemyAI: Combat ìƒíƒœ ì§„ì… - Target: %s"), *Target->GetName());
}

void AEnemyAI::EnterAlertState(const FVector& LastKnownLocation)
{
    if (!controlledEnemy) return;

    // === Alert ìƒíƒœë¡œ ì „í™˜ ===
    isInCombat = false;
    isAlert = true;
    isPatrolling = false;
    
    lastKnownTargetLocation = LastKnownLocation;
    alertTimer = 0.0f;
    
    // === ë¸”ë™ë³´ë“œ ì—…ë°ì´íŠ¸ ===
    UpdateBlackboardKeys();
    
    UE_LOG(LogTemp, Warning, TEXT("EnemyAI: Alert ìƒíƒœ ì§„ì… - Location: %s"), *LastKnownLocation.ToString());
}

void AEnemyAI::EnterPatrolState()
{
    if (!controlledEnemy) return;

    // === Patrol ìƒíƒœë¡œ ì „í™˜ ===
    isInCombat = false;
    isAlert = false;
    isPatrolling = true;
    
    currentTarget = nullptr;
    
    // === Enemy ê°ì²´ì— ì „íˆ¬ ëª¨ë“œ í•´ì œ ì•Œë¦¼ ===
    if (controlledEnemy->isInCombat)
    {
        controlledEnemy->ExitCombatMode();
    }
    
    // === ë¸”ë™ë³´ë“œ ì—…ë°ì´íŠ¸ ===
    UpdateBlackboardKeys();
    
    UE_LOG(LogTemp, Log, TEXT("EnemyAI: Patrol ìƒíƒœ ì§„ì…"));
}

void AEnemyAI::ClearAllStates()
{
    isInCombat = false;
    isAlert = false;
    isPatrolling = true;
    isBurstFiring = false;
    
    currentTarget = nullptr;
    alertTimer = 0.0f;
    combatTimer = 0.0f;
    
    if (controlledEnemy && controlledEnemy->isInCombat)
    {
        controlledEnemy->ExitCombatMode();
    }
    
    UpdateBlackboardKeys();
    
    UE_LOG(LogTemp, Log, TEXT("EnemyAI: ëª¨ë“  ìƒíƒœ ì´ˆê¸°í™”"));
}

// === ìƒíƒœ í™•ì¸ í•¨ìˆ˜ë“¤ ===

bool AEnemyAI::GetInCombat() const
{
    return isInCombat;
}

bool AEnemyAI::GetAlert() const
{
    return isAlert;
}

bool AEnemyAI::GetPatrolling() const
{
    return isPatrolling;
}

// === TPS Kit GASP ì‹œìŠ¤í…œ - ì—…ë°ì´íŠ¸ í•¨ìˆ˜ë“¤ ===

void AEnemyAI::UpdateGASPSystem(float DeltaTime)
{
    // === ğŸ”§ ì™„ì „íˆ ë¹„í™œì„±í™” - ë¹„í—¤ì´ë¹„ì–´ íŠ¸ë¦¬ì—ì„œë§Œ ì œì–´ ===
    return;
}

void AEnemyAI::UpdateCombatBehavior(float DeltaTime)
{
    // === ğŸ”§ ìë™ ì „íˆ¬ í–‰ë™ ì œê±° - ë¹„í—¤ì´ë¹„ì–´ íŠ¸ë¦¬ì—ì„œë§Œ ì œì–´ ===
    return;
}

void AEnemyAI::UpdateAlertBehavior(float DeltaTime)
{
    // === ğŸ”§ ìë™ ê²½ê³„ í–‰ë™ ì œê±° - ë¹„í—¤ì´ë¹„ì–´ íŠ¸ë¦¬ì—ì„œë§Œ ì œì–´ ===
    return;
}

void AEnemyAI::UpdatePatrolBehavior(float DeltaTime)
{
    // === ğŸ”§ ìë™ íŒ¨íŠ¸ë¡¤ ì™„ì „ ì œê±° - ë¹„í—¤ì´ë¹„ì–´ íŠ¸ë¦¬ì—ì„œë§Œ ì œì–´ ===
    return;
}

// === ğŸ”§ ì™„ì „íˆ ì œê±°ëœ í•¨ìˆ˜ë“¤ ===
// void AEnemyAI::UpdateMovementDirection(float DeltaTime) - ì œê±°ë¨

// === ğŸ”§ ì˜ì—­ íƒìƒ‰ ë° ì´ë™ í•¨ìˆ˜ë“¤ ì œê±° ===

AOccupiedTerritory* AEnemyAI::FindNearestFriendlyTerritory()
{
    // === ğŸ”§ ë¹„í—¤ì´ë¹„ì–´ íŠ¸ë¦¬ì—ì„œë§Œ í˜¸ì¶œë˜ë„ë¡ ì œí•œ ===
    if (!BehaviorTree || !GetBlackboardComponent()) return nullptr;
    
    if (!GetWorld() || !controlledPawn) return nullptr;

    TArray<AActor*> foundActors;
    UGameplayStatics::GetAllActorsOfClass(GetWorld(), AOccupiedTerritory::StaticClass(), foundActors);

    if (foundActors.Num() == 0) return nullptr;

    AOccupiedTerritory* nearestFriendlyTerritory = nullptr;
    float shortestDistance = FLT_MAX;
    FVector currentLocation = controlledPawn->GetActorLocation();

    for (AActor* actor : foundActors)
    {
        AOccupiedTerritory* territory = Cast<AOccupiedTerritory>(actor);

        if (territory && territory->IsFriendlyTerritory())
        {
            float distance = FVector::Dist(currentLocation, territory->GetActorLocation());

            if (distance < shortestDistance)
            {
                shortestDistance = distance;
                nearestFriendlyTerritory = territory;
            }
        }
    }

    return nearestFriendlyTerritory;
}

// === ğŸ”§ MoveToFriendlyTerritory, MoveToTargetLocation, OnMoveCompleted ì œê±° ===

// === ë¸”ë™ë³´ë“œ ë™ê¸°í™” í•¨ìˆ˜ë“¤ ===

void AEnemyAI::SyncEnemyStateWithBlackboard()
{
    // === ğŸ”§ ë¹„í—¤ì´ë¹„ì–´ íŠ¸ë¦¬ê°€ ì—†ìœ¼ë©´ ë¸”ë™ë³´ë“œ ë™ê¸°í™” ì•ˆí•¨ ===
    UBlackboardComponent* blackboardComp = GetBlackboardComponent();
    if (!blackboardComp || !controlledEnemy || !BehaviorTree) return;

    // === ğŸ”§ ì „íˆ¬ í•´ì œ ì¡°ê±´ í™•ì¸ ===
    CheckCombatDisengagementConditions(blackboardComp);

    // === Enemy â†’ Blackboard ë™ê¸°í™” ===
    blackboardComp->SetValueAsBool(BB_IsInCombat, controlledEnemy->isInCombat);
    blackboardComp->SetValueAsBool(BB_IsAlert, isAlert);
    blackboardComp->SetValueAsBool(BB_IsBurstFiring, controlledEnemy->isBurstFiring);
    
    // === íƒ€ê²Ÿ ì •ë³´ ì—…ë°ì´íŠ¸ ===
    if (controlledEnemy->currentTarget)
    {
        blackboardComp->SetValueAsObject(BB_TargetActor, controlledEnemy->currentTarget);
        blackboardComp->SetValueAsVector(BB_LastKnownPlayerLocation, controlledEnemy->currentTarget->GetActorLocation());
    }
    else if (!lastKnownTargetLocation.IsZero())
    {
        blackboardComp->SetValueAsVector(BB_LastKnownPlayerLocation, lastKnownTargetLocation);
    }
}

// === ğŸ”§ ìƒˆë¡œ ì¶”ê°€ëœ ì „íˆ¬ í•´ì œ ì¡°ê±´ í™•ì¸ í•¨ìˆ˜ ===
void AEnemyAI::CheckCombatDisengagementConditions(UBlackboardComponent* blackboardComp)
{
    if (!blackboardComp || !controlledPawn) return;

    // í˜„ì¬ ì „íˆ¬ ì¤‘ì¸ì§€ í™•ì¸
    bool currentIsInCombat = blackboardComp->GetValueAsBool(BB_IsInCombat);
    if (!currentIsInCombat) return;

    // FireDistance í™•ì¸
    float fireDistance = blackboardComp->GetValueAsFloat(BB_FireDistance);
    if (fireDistance < 800.0f) return;

    // ëª©í‘œ ì´ë™ ìœ„ì¹˜ í™•ì¸ (LastKnownPlayerLocationì„ ì´ë™ ëª©í‘œë¡œ ê°€ì •)
    FVector moveTargetLocation = blackboardComp->GetValueAsVector(BB_LastKnownPlayerLocation);
    if (moveTargetLocation.IsZero()) return;

    // í˜„ì¬ ìœ„ì¹˜ì—ì„œ ëª©í‘œ ì´ë™ ìœ„ì¹˜ê¹Œì§€ì˜ ê±°ë¦¬ í™•ì¸
    float distanceToMoveTarget = FVector::Dist(controlledPawn->GetActorLocation(), moveTargetLocation);

    // ì¡°ê±´ í™•ì¸: FireDistance >= 800 && ì´ë™ ëª©í‘œê¹Œì§€ ê±°ë¦¬ <= 500
    if (fireDistance >= 800.0f && distanceToMoveTarget <= 500.0f)
    {
        // ì „íˆ¬ ìƒíƒœ í•´ì œ
        isInCombat = false;
        
        // Enemy ê°ì²´ë„ ì „íˆ¬ ëª¨ë“œ í•´ì œ
        if (controlledEnemy && controlledEnemy->isInCombat)
        {
            controlledEnemy->ExitCombatMode();
        }

        // ë¸”ë™ë³´ë“œ ì¦‰ì‹œ ì—…ë°ì´íŠ¸
        blackboardComp->SetValueAsBool(BB_IsInCombat, false);
        blackboardComp->SetValueAsBool(BB_IsAlert, true); // Alert ìƒíƒœë¡œ ì „í™˜

        UE_LOG(LogTemp, Warning, TEXT("EnemyAI: ì „íˆ¬ í•´ì œ ì¡°ê±´ ì¶©ì¡± - FireDistance: %.1f, MoveDistance: %.1f"), 
            fireDistance, distanceToMoveTarget);
    }
}

// === ì „íˆ¬ ê´€ë ¨ í•¨ìˆ˜ë“¤ ===

void AEnemyAI::StartAttack()
{
    if (!controlledEnemy) return;
    
    isAttacking = true;
    controlledEnemy->StartGunFiring();
    
    UE_LOG(LogTemp, Warning, TEXT("EnemyAI: ê³µê²© ì‹œì‘"));
}

void AEnemyAI::StopAttack()
{
    if (!controlledEnemy) return;
    
    isAttacking = false;
    controlledEnemy->StopGunFiring();
    
    UE_LOG(LogTemp, Log, TEXT("EnemyAI: ê³µê²© ì¤‘ì§€"));
}

void AEnemyAI::StartBurstFire()
{
    if (!controlledEnemy || isBurstFiring) return;
    
    isBurstFiring = true;
    controlledEnemy->StartBurstFire();
    
    UE_LOG(LogTemp, Warning, TEXT("EnemyAI: ë²„ìŠ¤íŠ¸ íŒŒì´ì–´ ì‹œì‘"));
}

void AEnemyAI::StopBurstFire()
{
    if (!controlledEnemy || !isBurstFiring) return;
    
    isBurstFiring = false;
    controlledEnemy->StopBurstFire();
    
    UE_LOG(LogTemp, Log, TEXT("EnemyAI: ë²„ìŠ¤íŠ¸ íŒŒì´ì–´ ì¤‘ì§€"));
}

// === ì¸ì‹ ì‹œìŠ¤í…œ ===

void AEnemyAI::OnPerceptionUpdated(AActor* Actor, FAIStimulus Stimulus)
{
    if (!Actor || !controlledEnemy) return;

    // === í”Œë ˆì´ì–´ ê°ì§€ ì²˜ë¦¬ë§Œ ìœ ì§€ - ìƒíƒœ ë³€ê²½ì€ ë¸”ë™ë³´ë“œë¥¼ í†µí•´ì„œë§Œ ===
    if (APawn* detectedPawn = Cast<APawn>(Actor))
    {
        if (detectedPawn->IsPlayerControlled())
        {
            if (Stimulus.WasSuccessfullySensed())
            {
                // === ğŸ”§ ë¹„í—¤ì´ë¹„ì–´ íŠ¸ë¦¬ê°€ ìë™ìœ¼ë¡œ ì „íˆ¬ ëª¨ë“œ ì§„ì…í•˜ë„ë¡ ë¸”ë™ë³´ë“œ ì„¤ì • ===
                if (UBlackboardComponent* blackboardComp = GetBlackboardComponent())
                {
                    blackboardComp->SetValueAsObject(BB_TargetActor, Actor);
                    blackboardComp->SetValueAsVector(BB_LastKnownPlayerLocation, Actor->GetActorLocation());
                    
                    float distance = FVector::Dist(controlledPawn->GetActorLocation(), Actor->GetActorLocation());
                    blackboardComp->SetValueAsFloat(BB_FireDistance, distance);
                    
                    // ğŸ”§ IsInCombatì„ trueë¡œ ì„¤ì •í•˜ì—¬ Combat Sequence í™œì„±í™”
                    blackboardComp->SetValueAsBool(BB_IsInCombat, true);
                    blackboardComp->SetValueAsBool(BB_IsAlert, false); // Alert í•´ì œ
                    
                    UE_LOG(LogTemp, Warning, TEXT("EnemyAI: ì „íˆ¬ ëª¨ë“œ í™œì„±í™” - Distance: %.1f"), distance);
                }
                
                // Enemy ê°ì²´ë„ ì „íˆ¬ ëª¨ë“œë¡œ ì„¤ì •
                if (controlledEnemy && !controlledEnemy->IsInCombat())
                {
                    controlledEnemy->EnterCombatMode(Actor);
                }
            }
            else
            {
                // === í”Œë ˆì´ì–´ ì‹œì•¼ì—ì„œ ì‚¬ë¼ì§ ===
                if (UBlackboardComponent* blackboardComp = GetBlackboardComponent())
                {
                    blackboardComp->SetValueAsObject(BB_TargetActor, nullptr);
                    blackboardComp->SetValueAsBool(BB_IsInCombat, false);
                    blackboardComp->SetValueAsBool(BB_IsAlert, true); // Alert ëª¨ë“œë¡œ ì „í™˜
                    blackboardComp->SetValueAsFloat(BB_FireDistance, 9999.0f);
                }
            }
        }
    }
}

// === ìœ í‹¸ë¦¬í‹° í•¨ìˆ˜ë“¤ ===

bool AEnemyAI::CanSeeTarget(AActor* Target) const
{
    if (!Target || !controlledPawn || !AIPerceptionComp) return false;
    
    FActorPerceptionBlueprintInfo perceptionInfo;
    AIPerceptionComp->GetActorsPerception(Target, perceptionInfo);
    
    for (const FAIStimulus& stimulus : perceptionInfo.LastSensedStimuli)
    {
        if (stimulus.WasSuccessfullySensed())
        {
            return true;
        }
    }
    
    return false;
}

void AEnemyAI::DisplayDebugInfo()
{
    if (CVarShowEnemyAIDebug.GetValueOnGameThread() == 0 || !controlledEnemy) return;
        
    FString stateInfo;
    if (isInCombat)
        stateInfo = TEXT("COMBAT");
    else if (isAlert)
        stateInfo = FString::Printf(TEXT("ALERT (%.1fs)"), alertTimer);
    else
        stateInfo = TEXT("PATROL");
        
    if (isBurstFiring)
        stateInfo += TEXT(" | FIRING");
        
    FString targetInfo = TEXT("No Target");
    if (currentTarget)
    {
        float distance = FVector::Dist(controlledEnemy->GetActorLocation(), currentTarget->GetActorLocation());
        targetInfo = FString::Printf(TEXT("%s (%.0f)"), *currentTarget->GetName(), distance);
    }
    
    FVector location = controlledEnemy->GetActorLocation() + FVector(0, 0, 100);
    DrawDebugString(GetWorld(), location, stateInfo, nullptr, FColor::White, 0.0f, true);
    DrawDebugString(GetWorld(), location + FVector(0, 0, 15), targetInfo, nullptr, FColor::Yellow, 0.0f, true);
}

void AEnemyAI::UpdateTargetDistance()
{
    UBlackboardComponent* blackboardComp = GetBlackboardComponent();
    if (!blackboardComp || !controlledPawn) return;

    // í˜„ì¬ íƒ€ê²Ÿ ê°€ì ¸ì˜¤ê¸°
    AActor* target = Cast<AActor>(blackboardComp->GetValueAsObject(BB_TargetActor));
    
    if (target)
    {
        // íƒ€ê²Ÿê³¼ì˜ ê±°ë¦¬ ê³„ì‚°
        float distance = FVector::Dist(controlledPawn->GetActorLocation(), target->GetActorLocation());
        blackboardComp->SetValueAsFloat(BB_FireDistance, distance);
    }
    else
    {
        // íƒ€ê²Ÿì´ ì—†ìœ¼ë©´ ë§¤ìš° í° ê°’ìœ¼ë¡œ ì„¤ì •
        blackboardComp->SetValueAsFloat(BB_FireDistance, 9999.0f);
    }
}

void AEnemyAI::UpdateBlackboardKeys()
{
    UBlackboardComponent* blackboardComp = GetBlackboardComponent();
    if (!blackboardComp) return;

    // í˜„ì¬ ìƒíƒœë¥¼ ë¸”ë™ë³´ë“œì— ë™ê¸°í™”
    blackboardComp->SetValueAsBool(BB_IsInCombat, isInCombat);
    blackboardComp->SetValueAsBool(BB_IsAlert, isAlert);
    blackboardComp->SetValueAsBool(BB_IsBurstFiring, isBurstFiring);
    
    // íƒ€ê²Ÿ ì •ë³´ ì—…ë°ì´íŠ¸
    if (currentTarget)
    {
        blackboardComp->SetValueAsObject(BB_TargetActor, currentTarget);
        blackboardComp->SetValueAsVector(BB_LastKnownPlayerLocation, currentTarget->GetActorLocation());
        
        // íƒ€ê²Ÿê³¼ì˜ ê±°ë¦¬ë„ ì—…ë°ì´íŠ¸
        if (controlledPawn)
        {
            float distance = FVector::Dist(controlledPawn->GetActorLocation(), currentTarget->GetActorLocation());
            blackboardComp->SetValueAsFloat(BB_FireDistance, distance);
        }
    }
    else if (!lastKnownTargetLocation.IsZero())
    {
        blackboardComp->SetValueAsVector(BB_LastKnownPlayerLocation, lastKnownTargetLocation);
        blackboardComp->SetValueAsFloat(BB_FireDistance, 9999.0f);
    }
    
    // Self Actor ì„¤ì • (í•„ìš”í•œ ê²½ìš°)
    if (controlledPawn)
    {
        blackboardComp->SetValueAsObject(BB_SelfActor, controlledPawn);
    }
}